services:
  web-stats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-stats-app
    restart: always
    ports:
      # Direct IP Access via Port 3000 (http://<SERVER_IP>:3000)
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TARGET_SITE_NAME=okkabun.instiperjogja.ac.id
      - TARGET_SITE_URL=http://okkabun-nginx
      - DB_HOST=10.7.171.20
      - DB_PORT=3306
      - DB_USER=webstats_user
      - DB_PASSWORD=webstats_password
      - DB_NAME=web_stats_db
      - NGINX_LOG_PATH=/var/log/target/okkabun_logs/access.log
      - PROBE_INTERVAL_MS=15000
      - AGGREGATION_INTERVAL_MS=60000
    volumes:
      # Mount folder logs okkabun (Read-Only) untuk menghindari isu Docker membuat folder jika access.log belum ada
      - /srv/docker/okkabun.instiperjogja.ac.id/logs:/var/log/target/okkabun_logs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

networks:
  proxy:
    external: true
